_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
amp:
    value: true
batch:
    value: 16
box:
    value: 7.5
cache:
    value: false
close_mosaic:
    value: 10
cls:
    value: 0.5
cos_lr:
    value: false
data:
    value: /data/mvarela/datasets/corona-mosaic-dron/dataset-corona-mosaic-dron/data.yaml
degrees:
    value: 45
deterministic:
    value: true
device:
    value: None
dfl:
    value: 1.5
dropout:
    value: 0
entity:
    value: maria-varelacordero-universidad-de-costa-rica
epochs:
    value: 200
exist_ok:
    value: true
fraction:
    value: 1
freeze_all_layers:
    value: 27
freeze_backbone_layers:
    value: 10
hsv_h:
    value: 0.09
hsv_s:
    value: 0.7
hsv_v:
    value: 0.3
imgsz:
    value: 640
kobj:
    value: 2
label_smoothing:
    value: 0
lr0:
    value: 0.01
lrf:
    value: 0.01
mask_ratio:
    value: 4
mixup:
    value: 0.5
model:
    value: yolov8n.pt
model_yaml:
    value: yolov8.yaml
momentum:
    value: 0.937
mosaic:
    value: 0.5
name:
    value: yolov8n
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 20
plots:
    value: false
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: corona-mosaic-dron
rect:
    value: false
resume:
    value: false
save:
    value: true
save_path:
    value: /data/mvarela/yolo_weights/corona-mosaic-dron
save_period:
    value: -1
scale:
    value: 0.3
seed:
    value: 0
shear:
    value: 45
single_cls:
    value: false
time:
    value: None
training_mode:
    value: fine-tuning
translate:
    value: 0.3
val:
    value: true
verbose:
    value: false
warmup_bias_lr:
    value: 0.1
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 8
